#!/bin/sh

topdir=$(dirname "$0")

set -e

rm -f "$topdir/wishlist.json"
scrapy crawl wishlist -o "$topdir/wishlist.json" -t json -L INFO

rm -f "$topdir/library.json"
scrapy crawl library -o "$topdir/library.json" -t json -L INFO

"$topdir/page.py"
